In [10]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import Ridge,SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
x,y = load_diabetes(return_X_y = True)

In [3]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [74]:
r = Ridge(alpha=0.001, max_iter = 500,solver = 'sparse_cg')

In [75]:
r.fit(X_train,Y_train)

Ridge(alpha=0.001, max_iter=500, solver='sparse_cg')

In [76]:
pred = r.predict(X_test)

In [77]:
r2_score(Y_test,pred)

0.43733738906953945

In [78]:
r.coef_,r.intercept_

(array([ -30.48496796, -271.42295653,  529.16318434,  326.93930601,
        -511.22868296,  278.31640337,  -59.0775618 ,  130.55729129,
         638.37180159,   62.49917306]),
 np.float64(151.42114217458948))

In [103]:
sgd = SGDRegressor(penalty = 'l2',max_iter =500, eta0 = 0.1, learning_rate ='constant' , alpha = 0.001)

In [104]:
sgd.fit(X_train,Y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [105]:
pred2 = sgd.predict(X_test)

In [106]:
r2_score(Y_test,pred2)

0.4241450216050535

In [107]:
sgd.coef_,sgd.intercept_

(array([  12.5332399 , -149.52010338,  396.58232635,  244.81368914,
         -12.4222475 ,  -59.7757275 , -194.29757228,  131.03140493,
         324.0143713 ,  118.84594787]),
 array([154.86223114]))

Make our own class
--

In [120]:
class MeraGDRidge:
    def __init__(self,learning_rate,alpha, epoch):
        self.lr = learning_rate
        self.epoch = epoch
        self.alpha = alpha
        self.coef = None
        self.intercept = None

    def fit(self,x,y):

        self.coef = np.ones(x.shape[1])
        self.intercept = 0
        theta = np.insert(self.coef,0,self.intercept)

        x = np.insert(x,0,1,axis=1)

        for i in range(self.epoch):
            slopes = np.dot(x.T,x).dot(theta) - np.dot(x.T,y) + self.alpha*theta
            theta = theta - self.lr * slopes

        self.coef = theta[1:]
        self.intercept = theta[0]
        print(self.coef,self.intercept)

    def predict(self,x_test):
        return self.intercept + np.dot(x_test,self.coef)
    
        

In [171]:
sgdr = MeraGDRidge(0.005,0.001,500)

In [172]:
sgdr.fit(X_train,Y_train)

[  -0.66915682 -211.2522372   489.47524462  294.81396284  -35.05060878
  -95.40558052 -223.14519116  135.46761284  389.21865771  117.70685654] 151.4242440615075


In [173]:
pred3 = sgdr.predict(X_test)

In [174]:
r2_score(Y_test,pred3)

0.4336264455734462