In [3]:
from sklearn.datasets import make_regression

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
import numpy as np



In [21]:
x,y = make_regression(n_samples=5000,n_features=10, n_informative=1, n_targets=1,noise=17, random_state=13)

In [22]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
X_train.shape

(4000, 10)

In [24]:
lr = LinearRegression()

In [25]:
lr.fit(X_train,Y_train)

LinearRegression()

In [26]:
pred = lr.predict(X_test)

In [27]:
r2_score(pred,Y_test)

0.9253849397951704

In [28]:
lr.coef_,lr.intercept_

(array([ 5.70091570e-01, -6.27873614e-01,  6.35122248e+01, -2.74028009e-01,
        -2.89234933e-01,  3.29198168e-01, -2.59694128e-01, -3.71070730e-01,
         5.77869275e-02, -3.38746913e-01]),
 np.float64(0.03385662790753141))

Make our own STOCHASTIC GD CLASS
---

In [29]:
class SGDreg:
    def __init__(self,lr,epoch):
        self.lr = lr
        self.epoch = epoch
        self.coef = None
        self.intercept = None

    def fit(self,x,y):
        
        self.intercept = 0
        self.coef = np.ones(x.shape[1])

        for i in range(self.epoch):
            for j in range(x.shape[0]):

                idx = np.random.randint(0,x.shape[0])
                
                y_hat = self.intercept + np.dot(x[idx],self.coef)
                intercept_der = -2 * (y[idx] - y_hat)
                coef_der = -2 * (y[idx] - y_hat)*x[idx]
                
                self.intercept = self.intercept - (self.lr * intercept_der)
                self.coef = self.coef - (self.lr * coef_der)

        print(self.intercept,self.coef)

    def predict(self,x_test):
        return self.intercept + np.dot(x_test,self.coef)

In [79]:
sgd = SGDreg(0.01,1)

In [80]:
sgd.fit(X_train,Y_train)

-2.452939931368022 [-0.39950537 -1.27265834 62.65188756 -2.01467601 -3.84299209  2.98572906
  0.73625861 -1.64258974 -0.98148499 -0.47539857]


In [81]:
y_pred = sgd.predict(X_test)

In [82]:
r2_score(y_pred,Y_test)

0.9131894492269268

In [83]:
from sklearn.linear_model import SGDRegressor

In [84]:
sgd = SGDRegressor(learning_rate="constant" ,eta0=0.01)

In [89]:
sgd.coef_,sgd.intercept_

(array([ 2.72209949, -3.22010208, 61.54221012, -0.53925215, -1.67880903,
        -0.95387829, -0.38805348, -1.64087619, -1.06958587, -0.9550833 ]),
 array([-2.14087274]))

In [86]:
pr = sgd.predict(X_test)

In [87]:
r2_score(pr,Y_test)

0.909560328556222